# Speed Testing OSKAR

## Initial Imports

In [1]:
import pandas as pd
import numpy as np

## Converting raw speeds to detailed info

In [2]:
# Load CSV
raw = pd.read_csv("speed_raw.csv")

raw

     x    y    z         dt    db      b
0  400  400  400  62751.015  21.0  150.0
1   10   10  100     58.824  15.0   39.0
2  400  400    1    744.814   2.0    3.0
3  100  100  100        NaN   NaN    NaN

In [3]:
# Calulate box side length, channel area, area side length, and total source count
raw.insert(3, "n", raw.x * raw.y * raw.z)
raw.insert(3, "a", raw.x * raw.y)
raw.insert(3, "l", np.sqrt(raw.a))
raw.insert(3, "k", np.cbrt(raw.n))

# Calculate total elapsed time and time per block
raw.insert(9, "dt/db", raw.dt / raw.db)
raw.insert(11, "t", raw["dt/db"] * raw.b)

raw

,x,y,z,k,l,a,n,dt,db,dt/db,b,t
0,400,400,400,400.000000,400.0,160000,64000000,62751.015,21.0,2988.143571,150.0,448221.535714
1,10,10,100,21.544347,10.0,100,10000,58.824,15.0,3.921600,39.0,152.942400
2,400,400,1,54.288352,400.0,160000,160000,744.814,2.0,372.407000,3.0,1117.221000
3,100,100,100,100.000000,100.0,10000,1000000,NaN,NaN,NaN,NaN,NaN

In [5]:
# Save data to the calculation CSV
raw.to_csv("speed_all.csv", index=False)

## Calculate power law

The tight-bound time complexity should be dependent on three variables:

$\Theta\left(g(x,y,z)\right) | g(x,y,z) = \alpha {(xy)}^{\beta} z^{\gamma},\alpha,\beta,\gamma\in$

Where